### ISSUE TITLE
AER/FeatureExtraction/DatasetHandling/Recola_46.py does not work

### ISSUE THREAD

**Issue by clmpt** [LeBenchmark/Interspeech2021#2]
Hi,

I am trying to make the AER scripts work on my computer for the RECOLA dataset.
While I successfully created the environment thanks to the `environment.yml` file and successfully preprocessed the data with the `Preprocess.py` script, I have been unable to create the `data.json` file with the `Recola_46.py` script.

Indeed, every time I launch the script, I get the following error
```
Traceback (most recent call last):
  File "./FeatureExtraction/DatasetHandling/Recola_46.py", line 1, in <module>
    from DataClasses import *
ModuleNotFoundError: No module named 'DataClasses'
````

I reinstalled the `dataclasses` library, that comes with python since 3.7, but it did not change the error.

I also removed caps from the import (`from dataclasses import *` instead of `from DataClasses import *`) but I got this error
```
Traceback (most recent call last):
  File "./FeatureExtraction/DatasetHandling/Recola_46.py", line 66, in <module>
    main()
  File "./FeatureExtraction/DatasetHandling/Recola_46.py", line 22, in main
    fileDict = AudioSample()
NameError: name 'AudioSample' is not defined
```

Thus, I believe that you are using a custom module named `DataClasses.py`, called by the line below, and that is not present in the repository.
https://github.com/LeBenchmark/Interspeech2021/blob/08bcd974c864f5a39477928a1a91d37e7635596e/AER/FeatureExtraction/DatasetHandling/Recola_46.py#L1

Could you please confirm this and if possible provide the corresponding file ?

**Comment by SinaAlisamir** [comment]
Hello, yes, it is my bad, sorry, I uploaded the DataClasses file under "DatasetHandling", please let me know if that resolves the issue or any other issue you might encounter

**Comment by clmpt** [comment]
Thank you !
This resolved the issue.

However, when extracting wav2vec2 features, I get the following error:
```
Traceback (most recent call last):
  File "FeatureExtraction/wav2vec2.py", line 8, in <module>
    from featFuncs import loadFromJson
ModuleNotFoundError: No module named 'featFuncs'
```
I guess, that is also caused by a missing file.
Could you please upload it ?

PS: I did not create a new issue for that since it seems related.

**Comment by SinaAlisamir** [comment]
The file is now uploaded, 
Also, many thanks for reporting the issues.

**Comment by clmpt** [comment]
Thanks again for solving the issue.

I have one last question, that is not related to these issues.
I want to use the LeBenchmark model on RECOLA.
I can see the model is on HuggingFace, but I do not see how I can use it natively, as the `wav2vec2.py`script is made to work with `fairseq`only.
Am I missing something ?

**Comment by SinaAlisamir** [comment]
np.

Yes, it is true that it is done through `fairseq` and honestly, I do not know how `HuggingFace` ecosystem works so I can not really answer how you can use LeBenchmark models with that, sorry about that, ... maybe if you provide more information on what you want to do exactly I could be able to help you,

About `wav2vec2.py` script and RECOLA, it allows for chunking wav files before extracting features for memory issues since RECOLA files are 5 minutes each and it is recommend for wa2vec models to be split into 10 to 30 seconds in length. Otherwise the same underlying pytorch model is used so technically it should be possible to use it on any ecosystem built on top of pytorch.

**Comment by clmpt** [comment]
OK. Thank you for your time and help 🙂.

I will try getting more into HuggingFace to make it work with LeBenchmark.
If I cannot find a way, I will try to contact you.

Thanks again,
Clément

**Comment by SinaAlisamir** [comment]
Any time and good luck :)

**Comment by clmpt** [comment]
Hi,

I am still unable to use the scripts and the model.
Can i contact you by email ?
